name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.11
          work-dir: .
          buildozer-cmd: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
